### ISSUE TITLE
Setup failed error.

### ISSUE THREAD

**Issue by ttheekshanaw** [prabindh/darknet#10]
Hello,
  I get the setup failed error when i try to run the test.cpp sample in arapaho folder.
   ....
   23 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   24 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   25 route  16
   26 reorg              / 2    26 x  26 x 512   ->    13 x  13 x2048
   27 route  26 24
   28 conv   1024  3 x 3 / 1    13 x  13 x3072   ->    13 x  13 x1024
   29 conv    425  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 425
   30 detection
Loading weights from yolo.weights...Done!
Setup failed!

**Comment by prabindh** [comment]
Please build with _DEBUG in the compile flags. ie, add "-D_DEBUG" to the flags. This will print more detailed info on why it failed.

**Comment by ttheekshanaw** [comment]
30 detection
Setup: net.n = 31
net.layers[0].batch = 1
Loading weights from yolo.weights...Done!
Setup: layers = 32657, 1677115408, 419844064
Image expected w,h = [416][416]!
Error allocating boxes/probs, (nil)/0x7f8f4d110010 !
Setup failed!

**Comment by ttheekshanaw** [comment]
Hello.
    There was issue with adding the flags properly. :) Now its working after adding -DCUDA and -DCUDNN

**Comment by prabindh** [comment]
It should be -DGPU and -DCUDNN
