### ISSUE TITLE
Error when using GPU mode

### ISSUE THREAD

**Issue by L-CY** [prabindh/darknet#11]
It is OKay when I compile in CPU mode. However, when I switch to GPU mode, something goes wrong. To be more concrete, (1) running time is exactly the same when I use CPU mode; (2) totally wrong results. Can u help me?

**Comment by prabindh** [comment]
Please use the section (https://github.com/prabindh/darknet#how-to-file-issues) for providing additional information.

**Comment by L-CY** [comment]
Ubuntu14.04 Cuda8.0 cudnn5.1 Titan X pascal
I donwloaded the forked darknet (https://github.com/prabindh/darknet/tree/v3.77) and compiled darknet-
cpp-shared following the instructions. I set CPU=1 CUDNN=1 OPENCV=1 DEBUG=0 in makefile.
The I git clone https://github.com/prabindh/qt5-opencv3-darknet to use the shared library. I simply generated a executable file and type "./qt5_opencv3_darknet detect cfg/yolo.cfg yolo.weights data/dog.jpg" and I got this:
(https://cloud.githubusercontent.com/assets/17997252/23663606/0ed80d32-038e-11e7-9591-6e84aa196a0c.png)
It was correct if I set CPU=0 CUDNN=0 OPENCV=1 DEBUG=0 when I compiled the shared library.
Did I miss anything？ Thank you.

**Comment by prabindh** [comment]
If it works if GPU=0, then it can only mean that - the darknet-shared lib and Qt app are built with different options. Could you try adding the below line to qt5-opencv3-app.pro, after ensuring GPU=1 and CUDNN=1 in the darknet makefile ? This will ensure both are built with same flags.

`DEFINES += GPU`
`DEFINES += CUDNN`

**Comment by prabindh** [comment]
Marking https://github.com/prabindh/qt5-opencv3-darknet/issues/2 and https://github.com/prabindh/qt5-opencv3-darknet/issues/1 as potentially having same solution.

**Comment by L-CY** [comment]
It works! Thank you so much.
