### ISSUE TITLE
make error: arithmetic on a pointer to void

### ISSUE THREAD

**Issue by eisneim** [prabindh/darknet#12]
osx 10.12
./src/utils.c:34:20: fatal error: arithmetic on a pointer to void
        shuffle(arr+(start*size), num, size);

**Comment by prabindh** [comment]
You could potentially refer to the latest code from the branch darknet-cpp-windows, as it is fixed there (https://github.com/prabindh/darknet/tree/darknet-cpp-windows/src/utils.c). I will pull in the fix to the master after some more productising of the windows branch. Thanks for noting this.

**Comment by prabindh** [comment]
Could you also update the gcc version being used on your side ?

**Comment by eisneim** [comment]
@prabindh 
```
$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.0.0 (clang-800.0.42.1)
Target: x86_64-apple-darwin16.3.0
```

**Comment by eisneim** [comment]
@prabindh the window version's code fixed the issue 👍

**Comment by eisneim** [comment]
@prabindh just a quick question, i was using original and your fork of darknet-cpp to train my custom datasets(7 classes, 500x500resolution), they all fails randomly with segmentatiion fault after random iterations
```
[1]    31987 segmentation fault  ./darknet-cpp detector train fsd/fsd.data fsd/yolo-fsd.cfg
```
I'm not sure whether this is caused by my image files, so i use opencv to convert all my images to jpg, then i try to put tons of printf() in source code to see which step messed up the memory, but still no luck. maybe this time i'll try to use photoshop to batch conversion

any suggestions?
thanks

**Comment by prabindh** [comment]
Are the label files following Yolo format? 

Sent from Yahoo Mail on Android 
 
  On Thu, Mar 9, 2017 at 6:30 PM, Eisneim Terry<notifications@github.com> wrote:   
@prabindh just a quick question, i was using original and your fork of darknet-cpp to train my custom datasets(7 classes, 500x500resolution), they all fails randomly with segmentatiion fault after random iterations
[1]    31987 segmentation fault  ./darknet-cpp detector train fsd/fsd.data fsd/yolo-fsd.cfg

I'm not sure whether this is caused by my image files, so i use opencv to convert all my images to jpg, then i try to put tons of printf() in source code to see which step messed up the memory, but still no luck. maybe this time i'll try to use photoshop to batch conversion

any suggestions?
thanks

**Comment by eisneim** [comment]
it just failed randomly, i logged out the image and label just before it fails, but i can see no issue.

 i wrote a chrome extension for creating annotation: [https://github.com/eisneim/dl_annotator](https://github.com/eisneim/dl_annotator) scripts folder contains my scripts to generate yolo labels, 
each label: 
```
2 0.265196 0.137720 0.570056 0.515504
```
my scripts ensures each rect box's x,y value must be greater than 0 and less than 1.0
maybe i should check it's order, minX, minY always first

anyway, thanks for your reply

**Comment by prabindh** [comment]
After looking at https://github.com/eisneim/dl_annotator/blob/master/scripts/yolo_darknet.py, specifically 

`x = min(x1, x2) / width`

It appears that the labelling is incorrect. Please check https://github.com/prabindh/euclid/blob/master/euclid.py for the coordinate format for the bounding boxes of Yolo.

**Comment by eisneim** [comment]
@prabindh oh my! i just realized x  y  are center of rectangle! thank you

**Comment by prabindh** [comment]
Please do not forget to close the issue if it is fixed. Thanks. You can raise a separate issue, for the crash that happens if labels are invalid.

**Comment by eisneim** [comment]
thanks for your help, i got 30fps results

**Comment by prabindh** [comment]
Just to let you know, the windows port has now been merged into master. Thx
