### ISSUE TITLE
extern "C"

### ISSUE THREAD

**Issue by WillieMaddox** [prabindh/darknet#15]
Is the extern "C" necessary in network.h?  I've been able to compile darknet-cpp and libdarknet-cpp-shared.so just fine without it.  I mainly run the detector though so I'm not sure if other runners need it.

**Comment by prabindh** [comment]
Could you please share the Makefile used ?

**Comment by prabindh** [comment]
Specifically the config flags used.

**Comment by WillieMaddox** [comment]
Right, I forgot:
GPU=1
CUDNN=1
OPENCV=1
DEBUG=1 (or 0)
ARCH= -gencode arch=compute_52,code=[sm_52,compute_52]

**Comment by WillieMaddox** [comment]
Any more thought on this?

**Comment by prabindh** [comment]
Have you tried to use the shared library in any extern C++ application ? Or, have you been able to build arapaho yet with this change ? Thanks,

**Comment by prabindh** [comment]
Just to be clear:  The change is expected to help, when darknet is built with a C compiler, but needs to be integrated with a C++ application.
