### ISSUE TITLE
How to get labels using Arapaho

### ISSUE THREAD

**Issue by niuliang42** [prabindh/darknet#16]
Hi Prabindh, 
Your cpp warpper is cool, just what I need. But I am wondering how to get corresponding labels for boxes when using Arapaho? Or is that a TODO?

**Comment by prabindh** [comment]
It is a TO-DO.  Wondering if it is needed to be a string label, or just an index.

**Comment by niuliang42** [comment]
Thank you for your reply. And I prefer a string label.

**Comment by niuliang42** [comment]
Hi,
I made a pull-request so that we can get labels along with boxes. Please check [get string type labels](https://github.com/prabindh/darknet/pull/18)
