### ISSUE TITLE
Memory leak from arapaho.cpp

### ISSUE THREAD

**Issue by Efreeto** [prabindh/darknet#19]
I noticed there was a memory leak when I was running multiple instances of live video streams. It gradually slowed the computer down to an almost halt after 15 minutes.
This has gone away after I added free_image() functions in Detect() function before returning.

But I think the even better solution is to move away from using darknet's make_image() and just pass OpenCV image's data.
Also, resize_image() from darknet is quite slow. I got much faster performance using OpenCV's resize().

I can compile a pull request to switch to OpenCV if you want after a few days. I probably won't use ArapahoV2ImageBuff either.

**Comment by prabindh** [comment]
Quite a lot of cleanup to do there, I agree. I think a native-buffer being passed all the way to CUDA, or combining resize with the other CUDA operations might be the best bet for performance.....

**Comment by prabindh** [comment]
And yes, a PR would be nice. Thx
