### ISSUE TITLE
Windows w/out GPU

### ISSUE THREAD

**Issue by luketg8** [prabindh/darknet#24]
Is it possible to use in Windows without a GPU? I can compile with CUDA but cannot run inference due to my current work laptop not having a GPU.

**Comment by prabindh** [comment]
Detection can be run without GPU. By inference, you mean detection, or training part ? 
The training part running without GPU is not useful at all, as it is too slow.

**Comment by luketg8** [comment]
I have trained a model externally so that's not an issue, however to run inference will I have to change a pre processor definition?

**Comment by prabindh** [comment]
Yes - please remove GPU, CUDA, CUDNN definitions from build Makefiles. If you are using Arapaho for detection, please remove from Arapaho makefile as well as from the darknet Makefile.

**Comment by luketg8** [comment]
Thank you! I really appreciate it.
