### ISSUE TITLE
image size

### ISSUE THREAD

**Issue by xunkaixin** [prabindh/darknet#25]
the  width and height  are 416  in .cfg file, but my labeled image size is 1280*720, did i need cut the labeled image? or some other suggestion？ thank you

**Comment by prabindh** [comment]
Is this for training, or for detection ?

**Comment by xunkaixin** [comment]
training and detection

**Comment by prabindh** [comment]
The images are resized before feeding to the network. But during the process, features might become  small. Other than this there should not be an issue.

**Comment by xunkaixin** [comment]
thank you

**Comment by luketg8** [comment]
In this case would the output (box coordinates) of the network during detection be on the resized image of scaled to the original image?

**Comment by prabindh** [comment]
In the current system, all coordinates are relative, not absolute and hence resizing is not an issue. Please see arapaho tests for an example of how this works.

**Comment by luketg8** [comment]
Thank you again! I will have a look into it tomorrow.
