### ISSUE TITLE
Error: Couldn't open file: data/coco.names

### ISSUE THREAD

**Issue by LorenaGdL** [prabindh/darknet#26]
I have sucessfully compiled darknet-shared and arapaho in my Linux machine. However, when trying to run `arapaho.out`, this error appears: `Couldn't open file: data/coco.names`

I'm aware that such path is included in the `input.data` file, and I have tried to set both a path relative to the arapaho folder (`../data/coco.names`) and a full path. In both cases, the file can't be opened for unknown reasons...

Any ideas regarding this? Thank you in advance

**Comment by prabindh** [comment]
Could you share the full log with DEBUG enabled please ?

**Comment by LorenaGdL** [comment]
Hi @prabindh, thank you for your prompt response.

I have re-built darknet with DEBUG enabled, and after that replaced the libdarknet-cpp-shared.so (2.7MB) of the arapaho folder, re-built arapaho and run `./arapaho.out`

In the command line, I see nothing else but the previous error. I don't see any other log in external files.

```
ubuntu@tegra-ubuntu:/media/ubuntu/SDCARD64/darknet/arapaho$ ./arapaho.out 
Couldn't open file: ../data/coco.names
```

**Comment by prabindh** [comment]
I wasnot clear enough sorry - In the arapaho build, please add D_DEBUG ...

**Comment by LorenaGdL** [comment]
-D_DEBUG is included by default in the arapaho Makefile

**Comment by prabindh** [comment]
Without looking at your filesystem it is difficult for me to figure out whats wrong, but for a start - can you place the coco.names file in the same folder as arapaho, then modify the input.data, and try again ?

**Comment by LorenaGdL** [comment]
I was about to throw in the towel and use a pretty ugly workaround to make it work when I came across the  (stupid) problem: I generated the `input.data` file in my Windows machine and then copied it to the Ubuntu one - result: wrong CRLF (^M) line endings in the file, messing everything up in Linux 😢 

Thank you anyway for your time!

**Comment by prabindh** [comment]
Great to know.
