### ISSUE TITLE
Arapaho 0 detections, loading empty layer

### ISSUE THREAD

**Issue by halt9** [prabindh/darknet#28]
Hi,

I closed issue #17 because the scope of the original problem was surpassed, but this is a new problem I'm having. I got the latest version of the repo. When I try to load the net, it loads, the config files are all detected, but it detects 0 objects. Looking back, it detects the last layer to be 0. Note that these exact files work when I run test.cpp. However when I separate the initialization of arapaho and the detecting code, it does not work. Here's the output (with some logging added by me)

```
Loading names from /home/halt9/dark_ws/src/detector/src/coco.names
Using cfg file /home/halt9/dark_ws/src/detector/src/input.cfg
Using weight file /home/halt9/dark_ws/src/detector/src/input.weights
layer     filters    size              input                output
    0 conv     32  3 x 3 / 1   416 x 416 x   3   ->   416 x 416 x  32
    1 max          2 x 2 / 2   416 x 416 x  32   ->   208 x 208 x  32
    2 conv     64  3 x 3 / 1   208 x 208 x  32   ->   208 x 208 x  64
    3 max          2 x 2 / 2   208 x 208 x  64   ->   104 x 104 x  64
    4 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128
    5 conv     64  1 x 1 / 1   104 x 104 x 128   ->   104 x 104 x  64
    6 conv    128  3 x 3 / 1   104 x 104 x  64   ->   104 x 104 x 128
    7 max          2 x 2 / 2   104 x 104 x 128   ->    52 x  52 x 128
    8 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256
    9 conv    128  1 x 1 / 1    52 x  52 x 256   ->    52 x  52 x 128
   10 conv    256  3 x 3 / 1    52 x  52 x 128   ->    52 x  52 x 256
   11 max          2 x 2 / 2    52 x  52 x 256   ->    26 x  26 x 256
   12 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   13 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256
   14 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   15 conv    256  1 x 1 / 1    26 x  26 x 512   ->    26 x  26 x 256
   16 conv    512  3 x 3 / 1    26 x  26 x 256   ->    26 x  26 x 512
   17 max          2 x 2 / 2    26 x  26 x 512   ->    13 x  13 x 512
   18 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   19 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512
   20 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   21 conv    512  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 512
   22 conv   1024  3 x 3 / 1    13 x  13 x 512   ->    13 x  13 x1024
   23 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   24 conv   1024  3 x 3 / 1    13 x  13 x1024   ->    13 x  13 x1024
   25 route  16
   26 reorg              / 2    26 x  26 x 512   ->    13 x  13 x2048
   27 route  26 24
   28 conv   1024  3 x 3 / 1    13 x  13 x3072   ->    13 x  13 x1024
   29 conv    425  1 x 1 / 1    13 x  13 x1024   ->    13 x  13 x 425
   30 detection
Setup: net.n = 31
net.layers[0].batch = 1
Loading weights from /home/halt9/dark_ws/src/detector/src/input.weights...Done!
Setup: layers = 0, 0, 0 and classes 0
Image expected w,h = [416][416]!
Trying to allocate boxes of 0 * 0 * 0 amount, 16 size
Trying to allocate probs of 0 amount, 8 size

```

My code is attached. It uses ROS, so you can't really compile it without, but you can inspect it. It compiles without error, and its structure replicates arapaho's test.cpp exactly except for some of the code being in the constructor for ImageConverter and some of it being in its imageCB method. However, I don't see why this should lead to 0 detections or a blank last layer. I'm using the default YOLO v2 config of darknet.
[detector.txt](https://github.com/prabindh/darknet/files/973879/detector.txt)

**Comment by prabindh** [comment]
Interesting scenario: Is it likely that, the imageCB is called  in a different thread context than from where the class was constructed ? Perhaps confirm logging gettid().

**Comment by halt9** [comment]
That is a possibility. I will conduct some testing. In the meantime, should the layer loaded be 0x0x0? Or should that be different?

**Comment by halt9** [comment]
Unfortunately(or maybe not?), it seems that the creation and callback are in the same thread context.

**Comment by prabindh** [comment]
Can you do the creation/setup also in the imagecb (for debugging this only) one-time ?

**Comment by halt9** [comment]
Haha, wow, when I do that:
```
init done
Loading names from /home/halt9/dark_ws/src/detector/src/coco.names
Using cfg file /home/halt9/dark_ws/src/detector/src/input.cfg
Using weight file /home/halt9/dark_ws/src/detector/src/input.weights
*** Error in `/home/halt9/dark_ws/devel/lib/detector/detector_node': malloc(): memory corruption: 0x00000000010a2e10 ***
```

**Comment by prabindh** [comment]
Are you able to get past the memory corruption ?

**Comment by halt9** [comment]
No. However, I found [this repo](https://github.com/leggedrobotics/darknet_ros) that solves my problem. You might want to inspect `darknet_ros/darknet_ros/src/YoloObjectDetector.cpp` to see how the issue was solved.

**Comment by prabindh** [comment]
Ok. Thanks.
