### ISSUE TITLE
CPU version

### ISSUE THREAD

**Issue by tomicfish** [prabindh/darknet#29]
Could it maked wituout GPU and CUDN? (GPU=0 CUDNN=0)
If I make it without GPU and CUDN, is there anything else I need to set up?
e.g NVCC?
I have made the arapho.out, but I meet a error that Couldn't open file: data/coco.names when I run arapaho.
I check the test.cpp and arapaho.cpp and can not find the place where call the "data/coco.names".
Please tell me how to fix this problem.
PS: 1.  I have  copyed the weights, cfg, data and image files to the arapaho folder.
      2. My arapaho makefile 
arapaho: clean
	g++ test.cpp arapaho.cpp -D_DEBUG -I../src/ -I/usr/local/include/ -L/home/ssd/darknet/arapaho -ldarknet-cpp-shared -L/home/ssd/darknet/arapaho -L/usr/local/lib  -lopencv_stitching -lopencv_superres -lopencv_videostab  -lopencv_calib3d -lopencv_features2d -lopencv_objdetect -lopencv_highgui -lopencv_photo -lopencv_video -lopencv_ml -lopencv_imgproc -lopencv_flann -lopencv_core  -std=c++11 -o arapaho.out
	
clean:
	rm -rf ./arapaho.out

**Comment by prabindh** [comment]
Most likely data/coco.names is referred from your .data file, like in this (https://github.com/prabindh/darknet/blob/master/cfg/voc.data). Please check.

**Comment by prabindh** [comment]
No.

> If I make it without GPU and CUDN, is there anything else I need to set up?

**Comment by tomicfish** [comment]
I used the coco.names' absolute path to replace relative path in input.data, and it works!
Thanks!

**Comment by hank-nguyen** [comment]
Can I use multi-CPUs simultaneously? I would like to build a fast non-GPU model. Thank you.

**Comment by prabindh** [comment]
Are you referring to Detection ? Or training ?

**Comment by hank-nguyen** [comment]
Detection only, sorry for not clear. Many thanks.

**Comment by prabindh** [comment]
Multi-CPU is not available in current darknet.
