### ISSUE TITLE
Darknet returning garbage bounding boxes in Qt Event Loop

### ISSUE THREAD

**Issue by isgursoy** [prabindh/darknet#3]
https://github.com/prabindh/qt5-opencv3-darknet/issues/1
https://groups.google.com/forum/#!topic/darknet/LHIwhQ2l3pQ

I am opening issue here; it is about darknet, nothing to do with that qt5-opencv3-darknet pseudo example.

**Comment by prabindh** [comment]
Since this issue does not arise when running outside of Qt5 as done by other users, I am considering this low priority. If there is sufficient interest, can look at it.

**Comment by isgursoy** [comment]
You mean Qt 1, 2, 3, 4 are okay? :)
Qt is just a symptom, there is a heap corruption and you are considering this low priority.

**Comment by isgursoy** [comment]
Test Image: 
![test](https://cloud.githubusercontent.com/assets/2170245/23317943/2db7220a-fad9-11e6-9700-6888fa01d147.png)
Without QApplication: 
![withoutqapplication](https://cloud.githubusercontent.com/assets/2170245/23318296/738a9d92-fada-11e6-8c66-54f51ff2ecfc.png)
With QApplication:
![withqapplication](https://cloud.githubusercontent.com/assets/2170245/23317938/25749776-fad9-11e6-8573-db94036c0654.png)

**Comment by prabindh** [comment]
Igor, this is great. Are the wrong bounding boxes gone now ?

**Comment by isgursoy** [comment]
No Igor, QApplication is bringing false negatives as you see. I just want to visualize issue. Nothing changed.

**Comment by prabindh** [comment]
There was an update on Qt app (or  any other  app) that uses the shared library, in this https://github.com/prabindh/darknet/issues/11. Please check if it applies.

**Comment by isgursoy** [comment]
Does not work here. I tried both of the cpu and gpu versions.

Using same pri's for app and lib.

config.pri:
```
!CUDA_OFF{
        exists("/usr/local/cuda/version.txt") {    
            message("FOUND CUDA")             
            DEFINES+=CUDA_AVAILABLE             
            CONFIG+=CUDA_AVAILABLE               
            include(cuda.pri)
        }
    }
.
.
.
CONFIG+=c++14
QMAKE_CFLAGS_DEBUG +=-O0
QMAKE_CFLAGS_DEBUG +=-g
QMAKE_CFLAGS_RELEASE +=-Ofast
QMAKE_CFLAGS_RELEASE +=-O1
QMAKE_CXXFLAGS_RELEASE += -Ofast
QMAKE_CXXFLAGS_RELEASE += -O1
QMAKE_CXXFLAGS_WARN_ON = -Wall -Wno-unused-parameter -Wno-unused-function
```

cuda.pri
```
DEFINES += GPU
CONFIG+=GPU
#DEFINES += OPENCV
#CONFIG+= OPENCV
#DEFINES += DEBUG
#CONFIG+= DEBUG
#DEFINES += CUDNN
#CONFIG+= CUDNN
                               
for(_defines, CUDA_DEFINES):{                                 
    formatted_defines += -D$$_defines
}

CUDA_DEFINES = $$formatted_defines
```

**Comment by isgursoy** [comment]
Solution is `setlocale(LC_NUMERIC,"C");` right after QApplication ctor.
https://doc.qt.io/qt-5/qcoreapplication.html#locale-settings

**Comment by prabindh** [comment]
So it turns it the label read was incorrect ? Good information.

**Comment by isgursoy** [comment]
I am not sure, something wrong with float's, probably corruption.

**Comment by prabindh** [comment]
Added a commit for this. I see this is also mentioned in - http://doc.qt.io/qt-5/qcoreapplication.html

**Comment by prabindh** [comment]
https://github.com/prabindh/darknet/commit/cdff53ece784229c3fd122d3b8bd1da94eaeb178

**Comment by isgursoy** [comment]
good job, we are done.
