### ISSUE TITLE
Getting YOLO and Caffe C++ to work together

### ISSUE THREAD

**Issue by salmanmaq** [prabindh/darknet#31]
Reference to #30, we got detection working when compiling with the -DGPU and -DCUDNN flags. However, we need to classify the detections using the Caffe C++ API. When we integrate the code, errors in Caffe pop up. The Caffe C++ classifier works fine otherwise. 

Is there any other way to compile darknet-cpp without the given flags and still get detections  in GPU mode?

Thanks

Salman

**Comment by prabindh** [comment]
To make sure I understand - you are training caffe classifier with the detection output of darknet ? And, please explain "errors in Caffe pop up" ? (is it compile, or link, or where)

**Comment by salmanmaq** [comment]
Sorry for the confusion and a not so clear question. We have already
trained a classifier in Caffe. We are using the trained Caffe model to
classify all detections done by Darknet. After the detection and
classification steps, we use an auxiliary code to do some operations.

When we integrate the darknet-cpp code with our auxiliary code, it works
fine, provided we build it using the -DGPU and -DCUDNN flags. Similarly,
when we integrate Caffe and our auxiliary code (without darknet-cpp), it
works great. However, it fails to compile when we try to use the -DCUDNN
and -DGPU flags. The errors are related to undefined reference to some
Caffe methods.
And similarly, when we try to compile the whole thing darknet-cpp + Caffe +
our code, the compilation fails when we use the mentioned flags. The code
compiles fine when we don't use the flags, but then darknet-cpp doesn't
give any detections.

I understand the issue is quite irrelevant to this repo, but is there some
way I can compile darknet-cpp without the flags and still get detections in
GPU mode?

Thanks.

**Comment by prabindh** [comment]
Ok. If your need is to remove GPU/CUDNN, feel free to remove it from darknet build itself. ie, 

1. Remove GPU, CUDNN defines in the Makefile (comment out lines 16, 17)
2. Remove GPU, CUDNN defines in the arapaho Makefile

You only need to ensure both darknet and arapaho are built with the same flags.
Note: Training, without GPU, CUDNN will be very slow. I think you are only interested in detection in thi discussion.

**Comment by prabindh** [comment]
Does this help ?

**Comment by salmanmaq** [comment]
Sorry for the late response. It should work, but again this would result in detections in CPU mode, which is contrary to our requirements. The issue isn't exactly relevant to this repo, so I'll just close this thread. We ultimately had to ditch this pipeline for a Python one.
