### ISSUE TITLE
Detection not working with NVIDIA card of compute capability 6.0

### ISSUE THREAD

**Issue by LorenaGdL** [prabindh/darknet#33]
Hi,
So, far, I've been successfully testing the arapaho C++ detection samplein an Nvidia card of compute capability 5.2. Now, I want to run some tests in a more powerful card of compute capability 6.0. For that, I have properly modified the darknet Makefile to include the new GPU architecture.

However, once I do that, detection is no longer working, in none of the cards (network is loaded, detection apparently runs -no errors- but no single detection is ever output). From the official Darknet Google Group I see others have succesfully used compute capability 6.0 (and even 6.1)

So, my question is if this repo is compatible with compute_60 or not, and if it would be possible to update whatever necessary for that

Thank you so much in advance

**Comment by prabindh** [comment]
There are no compute-capability dependent code in this (that has been modified relative to the mainline). Which CUDA toolkit version is being used ? Can you try with CUDNN=0.

**Comment by LorenaGdL** [comment]
Sorry, my fault 😞 

I copied by error an old Makefile that had CUDNN=0 while compiling arapaho with CUDNN. Recompiling darknet with CUDNN solved the issue

Thanks

**Comment by prabindh** [comment]
whew. Thanks. Just for my information - what relative performance gain you see moving from 5 to 6 ?
