### ISSUE TITLE
Sync back up with original repo?

### ISSUE THREAD

**Issue by WillieMaddox** [prabindh/darknet#37]
Are there plans to sync this up with the original repo.  As of today.  This fork is 37 commits behind pjreddie master.  So, no lstm, no segmenter, etc.

**Comment by prabindh** [comment]
Yes, need to, must. Just tied up in a couple of other things might take a week or so. Also, some bugfixes are pending to be pushed. Thanks!

**Comment by prabindh** [comment]
I am planning though, to have a separate branch now for the upcoming changes.

**Comment by prabindh** [comment]
Done. It is at - https://github.com/prabindh/darknet/tree/merge_lstm_gru_jun17
Tag v5.1
What has been tested - Detect with GPU, CPU at this time. Training not yet tested.
Once this becomes stable, will merge to master.
Master stable is at v5.0, before this merge.

**Comment by prabindh** [comment]
@WillieMaddox  any inputs on this ?

**Comment by prabindh** [comment]
@WillieMaddox  keep forgetting this is a long weekend,

**Comment by WillieMaddox** [comment]
I haven't forgotten about this.  Super Busy.  Will try to test branch sometime this week.

**Comment by prabindh** [comment]
@WillieMaddox were you able to check this out ?

**Comment by prabindh** [comment]
Synced up.
