### ISSUE TITLE
The accuracy of "arapaho" is different from "darknet-cpp" ?

### ISSUE THREAD

**Issue by kidapu** [prabindh/darknet#38]
I have experimented fish detection accuracy using a) "darknet-cpp", b) "arapaho" with same model,cfg,data file.

And result is following. I think "arapaho" is less accurate than "darkent-cpp". 

### a) darknet-cpp
https://youtu.be/tDdYOK9UbTE
<img width="987" alt="screen shot 2017-06-26 at 13 25 21" src="https://user-images.githubusercontent.com/720154/27525328-cdf39b60-5a77-11e7-96eb-44ffd162d273.png">

### b) arapaho
https://www.youtube.com/watch?v=WfuLMdDtRfs

<img width="937" alt="screen_shot_2017-06-26_at_13_25_33" src="https://user-images.githubusercontent.com/720154/27525217-cb98756c-5a76-11e7-8a00-513eda623399.png">

Please tell me why such a thing happens when you know the cause m(_ _)m

※ I think this difference of accuracy can reproduce when using default coco.data & yolo.weights.

**Comment by prabindh** [comment]
Did you try with latest version of the tree, there is a color-conversion issue (https://github.com/prabindh/darknet/issues/35) that got fixed.

**Comment by kidapu** [comment]
@prabindh 
Sorry form my laziness of `git pull`!
I can fix my problem! Thank you very much for your quick advice!
