### ISSUE TITLE
undefined xxx in softmax cuda code with merge_lstm_gru_jun17

### ISSUE THREAD

**Issue by isgursoy** [prabindh/darknet#39]
/usr/local/cuda//bin/nvcc -DGPU -DCUDNN --machine 64 -gencode arch=compute_20,code=[sm_20,sm_21] -gencode arch=compute_30,code=sm_30 -gencode arch=compute_35,code=sm_35 -gencode arch=compute_50,code=[sm_50,compute_50] -gencode arch=compute_52,code=[sm_52,compute_52] -Xcompiler -fPIC -c --use_fast_math --ptxas-options=-v -I"/usr/local/cuda//include" -lcudart.so -lcufft.so -lcublas.so -lcurand.so -lcudnn.so -o bin/objs//softmax_layer_kernels_cuda.o src/darknetcpp/softmax_layer_kernels.cu 2>&1 | sed -r "s/\(([0-9]+)\)/:\1/g" 1>&2

_nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning)._

**src/darknetcpp/softmax_layer_kernels.cu:37: error: identifier "network_state" is undefined**

**src/darknetcpp/softmax_layer_kernels.cu:45: error: identifier "network_state" is undefined**

**src/darknetcpp/softmax_layer_kernels.cu:47: error: identifier "axpy_ongpu" is undefined**

_3 errors detected in the compilation of "/tmp/tmpxft_00003035_00000000-15_softmax_layer_kernels.compute_52.cpp1.ii"._

Looks like you changed "network" type in upstream with "network_state" here and there is no such thing.
Also axpy_ongpu should be axpy_gpu.

**Comment by prabindh** [comment]
Thanks for the report, let me check it, as many changes are ongoing. Can you confirm the last commit id in the tree ?

**Comment by isgursoy** [comment]
my snapshot is 2393d2948ac0ab37b6f5f24fde1ee6bf24722ec8 committed 6 days ago.

**Comment by prabindh** [comment]
I checked - this issue is present in mainline also, which is why I didnt hit it. Will update.

**Comment by prabindh** [comment]
The file concerned is no longer used or relevant in the new tree. The relevant function "forward_softmax_layer_gpu" now is implemented as a subset in "softmax_gpu" in blas_kernels.cu.  Confirm ?

**Comment by isgursoy** [comment]
Correct, but where is the network_state type and axpy_ongpu function?
https://github.com/pjreddie/darknet/blob/master/src/softmax_layer.c#L56
https://github.com/pjreddie/darknet/blob/master/src/blas_kernels.cu#L559

**Comment by prabindh** [comment]
To clarify: The new tree has no such thing as "network_state" (replaced by "network"), and does not have the file "softmax_layer_kernels.cu" at all. Please check latest tree and confirm.

**Comment by isgursoy** [comment]
Correct.
