### ISSUE TITLE
what_time_is_it_now() of merge_lstm_gru_jun17 does not compile with c++

### ISSUE THREAD

**Issue by isgursoy** [prabindh/darknet#40]
double then = what_time_is_it_now(); in region_layer.c should be disabled and what_time_is_it_now() has to be removed from utils.c in order to compile with g++.

**Comment by prabindh** [comment]
Thanks for the report. Can you confirm the last commit id in the tree ?

**Comment by isgursoy** [comment]
same, my snapshot is 2393d2948ac0ab37b6f5f24fde1ee6bf24722ec8 committed 6 days ago.

**Comment by prabindh** [comment]
I checked, and this code is commented out in mainline itself. Hence I did not face this. Will see what needs to be done if this is uncommented.

**Comment by prabindh** [comment]
New commit has changed code when uncommented..please check

**Comment by prabindh** [comment]
@isgursoy  were you able to check this out ?

**Comment by isgursoy** [comment]
I can not reach my dev environment at the moment but if it is compiling, done. Next job is finding why it does not return any detections. I will switch to this branch from my master again in few days, so I can check.

**Comment by prabindh** [comment]
@isgursoy  were you able to check it out ?
