### ISSUE TITLE
Faster cpu gemm

### ISSUE THREAD

**Issue by isgursoy** [prabindh/darknet#41]
What about that simple improvement?

void gemm_nn(int M, int N, int K, float ALPHA, 
             float *A, int lda,
             float *B, int ldb,
             float *C, int ldc)
{
    int i,j,k;
**#pragma omp parallel for**
    for(i = 0; i < M; ++i){
        for(k = 0; k < K; ++k){
            register float A_PART = ALPHA*A[i*lda+k];
            for(j = 0; j < N; ++j){
                C[i*ldc+j] += A_PART*B[k*ldb+j];
            }
        }
    }
}

**Comment by prabindh** [comment]
Do we have a build with amp flags on gcc ? I would much rather prefer openmp on gcc.

**Comment by isgursoy** [comment]
C++ AMP is a dead ms shit. We have CUDA in gpu build, best we can have in cpu side is OpenCL (+AMD bonus) for decent models or AVX and SSE2 for up to date and older guys. OpenMP is least efficient but easiest to implement.
In all case gemm deserves to be improved. I added omp pragma to my copy for now.

**Comment by prabindh** [comment]
Trying to find performance data for some existing CL kernels,

**Comment by isgursoy** [comment]
https://github.com/pjreddie/darknet/commit/616e6305e232c1bfa76bc70c2f48e31489807b52#diff-ee485e80dbd4792e05ef21a4b7436b6b

**Comment by prabindh** [comment]
This is for OpenMP I see. I can see another derivative fork from the discussion at, https://github.com/prabindh/darknet-cpp-windows/issues/1

**Comment by isgursoy** [comment]
little note: omp can use simd too.
