### ISSUE TITLE
Any idea of darknet dll for C# 

### ISSUE THREAD

**Issue by mcjjin** [prabindh/darknet#42]
Hi I am planning to transfer the arapaho to CLR dll for C# application But I find the network and layer struct and opencv Mat are used in arapaho which are so diffcult to figue out in CLR , So any one have idea with this?

**Comment by prabindh** [comment]
The Arapaho API does not deal with network/layer, and only deals with image data (when OpenCV is not used). Did you look at this ?

        bool Setup(ArapahoV2Params & p,
            int & expectedWidth,
            int & expectedHeight);

        bool Detect(
            ArapahoV2ImageBuff & imageBuff,
            float thresh,
            float hier_thresh,
            int & objectCount);

**Comment by mcjjin** [comment]
yes you are right, but the private API __Detect need to be rewrite into CLR format as it is used in Detect methods, Isn't it?

**Comment by prabindh** [comment]
You should use only the exported APIs from CLR, not private ones internal to the DLL,

**Comment by mcjjin** [comment]
Is that mean I can just export the setup and Detect and GetBoxes methods into CLR rather than the whole class? Sorry I am not really getting your point because I thought that the whole class need to be rewrite into CLR manged class for C# application

**Comment by prabindh** [comment]
No need to wrap entire class. Create C++ DLL with exports for 3 functions - Setup, Detect, Teardown. Inside these, do the same things being done in the test.cpp appropriately. Let me know if this is not clear.

**Comment by prabindh** [comment]
Are you able to make progress ?

**Comment by mcjjin** [comment]
Yes I have made progress based on the DLL export from https://github.com/AlexeyAB/darknet and Now it is being used in my C# program:)
