### ISSUE TITLE
Detection results are different from original code

### ISSUE THREAD

**Issue by bobeo** [prabindh/darknet#47]
hi @prabindh ,

I've trained tiny yolo model on my custom objects. It went well and detection also works okay. However, on some images, detection fails and I decided to do a quick test:

I compile "make darknet", and then run ./darknet detector test on the image and it detects objects perfectly.

I compile the shared lib "make darknet-cpp-shared, and then "make arapaho" then run ./arapaho.out on the same image, the result is different( even the probs are also very different ) and not as good as one of running the original ./darknet

What is the different part of the code that could lead to this variation? My guess is that converting image from opencv Mat to "image" is the origin of the issue but then why does it work most of the time and just fails on a couple of images?

Thanks.

**Comment by bobeo** [comment]
To follow up, in arapaho.cpp, if I replace 

```
// Convert the bytes to float
        cv::Mat floatMat;
        inputRgb.convertTo( floatMat, CV_32FC3, 1 / 255.0 );

        if( floatMat.rows != net.h || floatMat.cols != net.w )
        {
            //        DPRINTF( "Detect: Resizing image to match network \n" );
            resize( floatMat, floatMat, cv::Size( net.w, net.h ) );
        }
        // Get the image to suit darknet
        std::vector<cv::Mat> floatMatChannels( 3 );
        split( floatMat, floatMatChannels );
        vconcat( floatMatChannels, floatMat );

        __Detect( reinterpret_cast<float*>( floatMat.data ), thresh, hier_thresh, objectCount );
```

by 

```
IplImage ipl_img = inputRgb;
        image im = IPL2Image( &ipl_img );
        image sized = letterbox_image( im, net.w, net.h );
        __Detect( sized.data, thresh, hier_thresh, objectCount );
        free_image( im );
        free_image( sized );
```

Then it will work correctly. But the returned bounding boxes are wrong in height.

Note this happens when the target image size( less then 200pixels wide ) is smaller than the trained image size( which is 416x416 )

**Comment by prabindh** [comment]
What is the height of the target image you are using ?

**Comment by bobeo** [comment]
hi @prabindh

Size of training images are variant, but both width and height are always less than 416. Same for target images.

In the .cfg file, we train with default size 
width=416
height=416 

Cheers,

**Comment by prabindh** [comment]
I understand the training sizes, I just wanted to understand sizes typically encountered in the image set you have. Since the original code tries to keep the aspect ratio similar to the original, it might give better results. Hence I wanted to know - which images w/h have an issue.

**Comment by bobeo** [comment]
One of the failed ones is 188 x 120 .

Both training and target images has width from 100 - 300 pixels, and height from 20 - 120 pixels. Yeh I saw the original code keeps the aspect ratio same as the original ratio. Why would you want to do it differently?

Thanks.

**Comment by prabindh** [comment]
You are right, I just did not encounter it in my use-cases. Will add to my que. I hope you have a workaround for now.

**Comment by bobeo** [comment]
Yeh, in case target images are less than trained size, then I will use the original image resize code. But I have to remember the scale in x and y, and use it to multiply with the final width and height of the object bounding box, else either width or height of the bounding box will be incorrect.

```
int new_w = im.w;
        int new_h = im.h;
        if( ( static_cast<float>( net.w ) / static_cast<float>( im.w ) ) <
            ( static_cast<float>( net.h ) / static_cast<float>( im.h ) ) )
        {
            new_w = net.w;
            new_h = ( im.h * net.w ) / im.w;
        }
        else
        {
            new_h = net.h;
            new_w = ( im.w * net.h ) / im.h;
        }
        rScaleX = static_cast<float>( net.w ) / static_cast<float>( new_w );
        rScaleY = static_cast<float>( net.h ) / static_cast<float>( new_h );
```

Cheers.

**Comment by bobeo** [comment]
hi @prabindh ,
Its not related to this issue but can I ask if there is a way to release GPU memory after calling load_weights() in ArapahoV2::Setup()? So if I run nvidia-smi, the memory usage should drop.

Many thanks,

**Comment by ooobelix** [comment]
Hi bobeo, I have reproduced your issue and update your code.

Have a look: Differences scores between Darknet and Arapaho #72

And I have the same issue on height... did you fix it? Thanks

**Comment by prabindh** [comment]
@ooobelix Can you please check this letterbox resize and see if it works for your case - https://gist.github.com/prabindh/852787042c1f0246132ffa4b17f4e220

**Comment by prabindh** [comment]
With @ooobelix changes integrated, this issue should be closed.
