### ISSUE TITLE
ArapahoV2ImageBuff

### ISSUE THREAD

**Issue by bwkchee** [prabindh/darknet#5]
Would it be easier to use a cv mat in ArapahoV2.Detect since opencv is required?  Is this the proper conversion for a cv::mat? 

Mat image = imread(input, CV_LOAD_IMAGE_COLOR);
w = image.rows
h = image.cols;
bgr = image.reshape(1,1);

**Comment by prabindh** [comment]
A bit more is required, for interfacing with yolo. Can you please check the latest commit of test.cpp, and provide your inputs ? The updated file adds support for CV image.

https://github.com/prabindh/darknet/blob/master/arapaho/test.cpp

**Comment by prabindh** [comment]
Arapaho now fully supports a test cycle - opening an image with OpenCV, running a detection with the C++ API, and dumping the object boundaries. Please check and update, if found ok, please close the issue. Thanks.

**Comment by prabindh** [comment]
Announcement: Tag https://github.com/prabindh/darknet/tree/v4.01 is now released, with further compile fixes for Mac and windows, and Arapaho readme. For windows builds please use https://github.com/prabindh/darknet-cpp-windows
