### ISSUE TITLE
when compile arapaho folder, there is the error about opencv,how to fix?

### ISSUE THREAD

**Issue by DanLiu0623** [prabindh/darknet#50]
/usr/bin/ld: cannot find -lopencv_cudabgsegm
/usr/bin/ld: cannot find -lopencv_cudaobjdetect
/usr/bin/ld: cannot find -lopencv_cudastereo
/usr/bin/ld: cannot find -lopencv_shape
/usr/bin/ld: cannot find -lopencv_cudafeatures2d
/usr/bin/ld: cannot find -lopencv_cudacodec
/usr/bin/ld: cannot find -lopencv_cudaoptflow
/usr/bin/ld: cannot find -lopencv_cudalegacy
/usr/bin/ld: cannot find -lopencv_videoio
/usr/bin/ld: cannot find -lopencv_imgcodecs
/usr/bin/ld: cannot find -lopencv_cudawarping
/usr/bin/ld: cannot find -lopencv_cudaimgproc
/usr/bin/ld: cannot find -lopencv_cudafilters
/usr/bin/ld: cannot find -lopencv_cudaarithm
/usr/bin/ld: cannot find -lopencv_viz
/usr/bin/ld: cannot find -lopencv_cudev
collect2: error: ld returned 1 exit status
make: *** [arapaho] Error 1

**Comment by prabindh** [comment]
Please install OpenCV on your machine. For example you can use OpenCV 3.1.  Usually it gets installed under /usr/local/lib

**Comment by DanLiu0623** [comment]
@prabindh I had install opencv by command: sudo apt-get install libopencv-dev, and the opencv version is 2.4.9. Should I must install opencv3.1?

**Comment by prabindh** [comment]
It appears the CV version you have does not support CUDA, hence most of the errors. You would need to install CV with CUDA support. For example, https://github.com/NervanaSystems/neon/issues/265

**Comment by DanLiu0623** [comment]
I have install cv with CUDA support,but another error occurs. It seems cv's issue. When I make arapaho in arapaho folder,the log is [log.txt](https://github.com/prabindh/darknet/files/1466771/log.txt).

**Comment by prabindh** [comment]
Please ensure the compilers used to build CV and darknet are compatible, and it is OpenCV 3.x.
