### ISSUE TITLE
No Detection w/ Tiny Yolo

### ISSUE THREAD

**Issue by oldgalileo** [prabindh/darknet#54]
Running on macOS 10.13.1 with OpenCV version 3.4.0 and no GPU, I can't get tiny-yolo.weights to run correctly but I _can_ get yolo.weights to run. 

Downloading them from https://pjreddie.com/darknet/yolo/ from the COCO trainval stuff, I can only get the "YOLOv2 608x608" weights to work. I'm running with GPU and CUDNN set to `0`, and using the command:
```
$ ./darknet-cpp detector demo cfg/coco.data cfg/yolo.cfg yolo.weights
```
This works fine and properly displays its predictions. However, using "Tiny YOLO" weights, and running the command:
```
$ ./darknet-cpp detector demo cfg/coco.data cfg/tiny-yolo.cfg tiny-yolo.weights
```

Nothing is detected it just displays the camera output. It is, however, taking a while to run and the FPS is pretty low, so it seems as though something is happening.

Thanks!

**Comment by oldgalileo** [comment]
Actually, the "Tiny YOLO VOC" weights work as well:
```
$ ./darknet-cpp detector demo cfg/voc.data cfg/tiny-yolo-voc.cfg tiny-yolo-voc.weights
```

**Comment by oldgalileo** [comment]
Okay, so after more sleuthing, it looks like it's an issue with prabindh/darknet not being able to handle weights which have a version of 0.2 or really just a minor version of 2 here. 

This can be seen in the line:
```
Loading weights from yolo.weights...mj = 0, mn = 1, *(net->seen) = 32013312
```
Which gets outputted when darknet loads the model (`src/parser.c`). Any hope of supporting the new weights format @prabindh ?

**Comment by prabindh** [comment]
Thanks, I could definitely look into it, but what is in the version (2), that makes it interesting ?

**Comment by tmigone** [comment]
Any updates on this topic?
I might be able to help if you can give me a few pointers as to where to look.

**Comment by prabindh** [comment]
Latest master is in sync with mainline. Please check tag v6.0 or master, and update.

**Comment by tmigone** [comment]
Updated and works like a charm. Thanks!!
Having trobule with the box sizes but i think is due to my code on top of arapaho.

**Comment by prabindh** [comment]
Can we close this then please ?

**Comment by tmigone** [comment]
Yes definitely

**Comment by prabindh** [comment]
@tomasmigone @HowardStark - I have started a small initiative to keep prebuilt binaries for quick verification of builds - for different OSs - Tegra, Linux, Windows, Mac. This repo is at (https://github.com/prabindh/yolo-bins). Is it possible to share prebuilt binaries (arapaho, darknet-cpp, libdarknet) with whatever toolchain you have, for MacOS ? Thanks a lot.

**Comment by oldgalileo** [comment]
Hey! I'm out of town for the next few days but when I get back I'd be more than happy to post them. Feel free to poke me if I don't remember within the next week or so.

**Comment by prabindh** [comment]
@HowardStark  Pinging on prebuilt binaries for MacOS, along with tool info... Thanks !
