### ISSUE TITLE
Missing functions

### ISSUE THREAD

**Issue by jdvylder** [prabindh/darknet#55]
Hi

It seems that some functions available in the original c darknet framework are not present in the branch.
Some examples in network.c:

- network_width(network *net)
- reset_rnn(network *net)
- network_height(network *net)
- etc.

Is there a specific reason that these functions have been discarded, or is it a matter of implementation time and are they not ported yet?

Thanks

**Comment by prabindh** [comment]
If you are looking at the main branch, yes, it is tracking an older stable version. Later version of the code (when lstgm/gru were added) is tracked in the branch (merge_lstm_gru_jun17). For example, network_width() function is available at,

https://github.com/prabindh/darknet/blob/merge_lstm_gru_jun17/src/network.c

**Comment by prabindh** [comment]
Please check latest master (tag v6.0) and confirm.
