### ISSUE TITLE
Arapaho stream with camera

### ISSUE THREAD

**Issue by lucCult** [prabindh/darknet#56]
Hi, how can I run araphao on a camera stream instead of a video file?

**Comment by prabindh** [comment]
Is this on Windows, or on Linux ?

**Comment by lucCult** [comment]
on Linux

**Comment by prabindh** [comment]
Replacing this line 
>> VideoCapture cap ( INPUT_AV_FILE );
with the below should work for the default camera on the system.
>> VideoCapture cap(0); // open the default camera

**Comment by prabindh** [comment]
Closing due to lack of response. Please reopen if needed.
