### ISSUE TITLE
input.data

### ISSUE THREAD

**Issue by zjtgit** [prabindh/darknet#58]
" Copy the weights, cfg, data and image files for detection into the arapaho folder." , what is the input.data? how can I get this file?

**Comment by turkishviking** [comment]
Look at  [the original repository](https://github.com/pjreddie/darknet/tree/master/cfg)
there is some ".data", basically it represent the dataset (testset, trainset, and more important for you, the label names). if you use a model trained on coco, use coco.data, etc...
visit [darknet site](https://pjreddie.com/darknet/yolo/) to know which model is trained on which dataset.

**Comment by zjtgit** [comment]
Got it, thanks for your reply.
