### ISSUE TITLE
calculating the filter value

### ISSUE THREAD

**Issue by MyVanitar** [prabindh/darknet#6]
Hi,

You mentioned:

> yolo-voc.cfg - change the number of filters in the CONV layer above the region layer - #classes + #coords(4) + 1)*(NUM)

if I am right, the formula would be: `(classes + coords + 1) * NUM`

May I ask you what are the values of `coords` and `NUM`?

**Comment by prabindh** [comment]
Please, see the updated README. I have changed it to be more clear.

For example, for #of classes = 2, size will be 35.

**Comment by VanitarNordic** [comment]
Nice, Thumbs up. I have open issues on your other repositories which I appreciate you reply sir.

**Comment by MyVanitar** [comment]
I appreciate if you reply my another question here: https://github.com/prabindh/qt5-opencv3-darknet/issues/2

it is open for around 5 days with no rely.
