### ISSUE TITLE
0 prediction with arapaho build (Yolo V3)

### ISSUE THREAD

**Issue by turkishviking** [prabindh/darknet#60]
git log : b177eed22ad3ab7335d2171b12e2a91e6829fbff
GPU=1
CUDNN=1
OPENCV=1

Linux Mint 18.3 (~Ubuntu 16.04)
OpenCV: 3.4.0
Cudnn 5.1
Cuda 8

Hi Prabindh, 
I'm testing the V3 version, when using 'make darknet-cpp', with weights files from https://pjreddie.com/darknet/yolo/ (yoloV3-608) all is fine.
But when I try with the same configuration to 'make arapaho' (with libdarknet-cpp-shared.so pre-build with same configuration too), I have 0 prediction (and no crash / error log)
Any idea of what I could do wrong?

Edit:
- I have tried all this afternoon, with the same input.weight and input cfg the two version (darknet-cpp and arapaho), the darknet-cpp works, the arapaho doesn't detect anything, can it be related to the input.data ? 

- tried to compile darknet-cpp-shared without opencv, --> detections == 0

- Image seems valid, I can see it in cv::NamedWindow, and print it:
`Image data = 0x7fe3a586f040, w = 768, h = 576
`

- Also checked layers:
```cpp
net = `parse_network_cfg(cfgfile);`

layer l0 = net.layers[0];
cout << l0.w << endl;
layer l1 = net.layers[1];
cout << l1.w << endl;
layer l = net.layers[net.n - 1];
cout << l.w << endl;
```
Which give me
```
416
416
52
```

**Comment by prabindh** [comment]
Please check latest master.  There were changes to be done for iterating through the detections.

**Comment by turkishviking** [comment]
Ok, I was modifying exactly the same things to make a pull request, cool, that's work, thank's!
