### ISSUE TITLE
upsample_cpu is not defined when GPU=0

### ISSUE THREAD

**Issue by hjchai** [prabindh/darknet#61]
I think you probably put this [line](https://github.com/prabindh/darknet/blob/master/src/blas.h#L65) in the wrong place.

I moved it up to the first section after _**void softmax_cpu(...)**_

**Comment by prabindh** [comment]
Please check master with this change done. Thanks !

**Comment by prabindh** [comment]
@Jitesh7 Since you had also reported this, please check master.
