### ISSUE TITLE
Cuda 9

### ISSUE THREAD

**Issue by bobeo** [prabindh/darknet#66]
Hi Prabindh,

Will this work with cuda 9?

Thanks.

**Comment by prabindh** [comment]
I have run it successfully with CUDA9.0 on the system (Windows). But this was a build compiled for CUDA8. I dont foresee issues compiling for CUDA9.0. Are you seeing any ?

**Comment by bobeo** [comment]
hi Prabindh,

I tried the darknet and darknet-cpp binary and it worked fine with cuda 9.0 and cudnn 7.1. But with arapaho, it didn't work. Specifically, this line:
```
DPRINTF("Setup: layers = %d, %d, %d\n", l.w, l.h, l.n);
```
is printed as: Setup: layers = 0,0,0

and it doesn't detect anything. 

Thanks.

**Comment by bobeo** [comment]
Not even with arapaho, I tested the minimal code, and it always give Setup: layers = 0,0,0. The minimal code is the function test_detector() in detector.c. What I dont understand is darknet-cpp uses the same code and it just works fine. Is there any difference when compiling darknet-cpp and libdarknet-cpp-shared.so?

Thanks.

**Comment by prabindh** [comment]
I am able to run the Arapaho app on Windows, with CUDA9.1. Please check whether the 3 options (GPU, CUDA, CUDNN) are the same in both cases - the DLL (.so) build, and your application (that  uses the DLL/.so).

**Comment by bobeo** [comment]
hi Prabindh,

My bad, I forgot to add -DCUDNN when compiling the application. It works fine.

Thanks.

**Comment by prabindh** [comment]
Great. Thanks for the update.
