### ISSUE TITLE
darknet-cpp compilation failed on Ubuntu 16.04

### ISSUE THREAD

**Issue by ooobelix** [prabindh/darknet#67]
Hi,

my goal is to build CPP Darknet thanks "_make darknet-cpp_" on Ubuntu 16.04 with latest version v6.4 but:

> ./examples/classifier.c:682:26: error: invalid conversion from ‘void*’ to ‘int*’ [-fpermissive]
>      int *indexes = calloc(top, sizeof(int));
> 

I can see in the logs that I compiling with c++0x

> ...
> g++ -Iinclude/ -Isrc/ -DOPENCV `pkg-config --cflags opencv`  -DGPU -I/usr/local/cuda/include/ -DCUDNN  -Wno-write-strings -std=c++0x -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC -Ofast -DOPENCV -DGPU -DCUDNN -c ./src/cost_layer.c -o obj-cpp/cost_layer.o
> ...

But as you have said:

> Note: darknet-cpp requires a C++11 compiler for darknet-cpp, and arapaho builds.

So I modify the Makefile as follow without success, same issue:

> --CFLAGS=-Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC
> ++CFLAGS=-std=c++11 -Wall -Wno-unused-result -Wno-unknown-pragmas -Wfatal-errors -fPIC

Finaly I modify examples/classifier.c as follow and it works better:

> --    int *indexes = calloc(top, sizeof(int));
> ++    //int *indexes = calloc(top, sizeof(int));
> ++    int *indexes = (int *) malloc(sizeof(int)*top);

But it failed on this:

> darknet.c:(.text.startup+0x39a) : undefined reference to « run_isegmenter(int, char**) »

Thanks in advance

**Comment by prabindh** [comment]
Last update on Linux front was this commit - https://github.com/prabindh/darknet/commit/01365fbea88b461f19715fdbadc6dbe89f5573a4

The later updates were on Windows, hence Linux build is broken. Let me fix it.

**Comment by prabindh** [comment]
The corresponding tag for the last Linux build was v6.2.

**Comment by prabindh** [comment]
@ooobelix  Please check latest master that resolves this, and also moves to latest mainline code. I will do more checks on the latest build soon.

**Comment by ooobelix** [comment]
Hi @prabindh, thanks for your job and fixes! Compilation under Ubuntu 16.04 on v6.5-1-g372b25d is working.

I have some questions:

- the commit 98e2a7674fd6a81349735db6f5b34229c871113a disable the use of OpenCV and GPU? If yes, is it working with GPU support?
- the commit a12730a124dd6c7d33f42eb2b78450c7b6379965 show some conflicts merge like "++>>>>>>> upstream/master"

Thanks again for your job!

**Comment by prabindh** [comment]
On below - this is a merge issue, will update.
- the commit a12730a show some conflicts merge like "++>>>>>>> upstream/master"
On the below, havent had time to check the actual build, will update. You can enable it and try and update as well.
- the commit 98e2a76 disable the use of OpenCV and GPU? If yes, is it working with GPU support ?

**Comment by ooobelix** [comment]
Ok. Thanks again for your job!
