### ISSUE TITLE
Memory corruption of Arapaho from a library

### ISSUE THREAD

**Issue by ooobelix** [prabindh/darknet#69]
Hi,

if I use Arapaho object since a simple test code thanks "_ArapahoV2* p = new ArapahoV2();_", like your "_test.cpp_", it works well.

If I use the same line into a constructor of home made cpp library, I have an "_*** Error in `./arapaho': malloc(): memory corruption: 0x0000000001985860 ***_"

Is it normal? I know that my issue is not complete and easy to reply.

**Comment by prabindh** [comment]
Are the library and the application built with similar  toolchain options ? Malloc/free issues typically crop up when either the toolchain is different or some options are different.

**Comment by ooobelix** [comment]
I do agree and I have checked the toolchain... without success.

My lib, including Arapaho, is a shared so, compiled with CMake:

> -g -DCUDNN -Ofast -fPIC -L/usr/local/cuda/lib64
> set (CMAKE_CXX_STANDARD 11)

**Comment by ooobelix** [comment]
Because I'm compiling with "_-shared_" option?

**Comment by ooobelix** [comment]
Ok I go back to my original code and right compilation option without problem.
Sorry for the disturb, do not take care of this issue.
