### ISSUE TITLE
Linking libdarknet-cpp-shared.so

### ISSUE THREAD

**Issue by prabindh** [prabindh/darknet#7]
On behalf of Willie, from thread @ https://mail.google.com/mail/u/0/#inbox/157f11cff62006e4,

 Has anyone had any success linking and using the libdarknet-cpp-shared.so library?

I've been able to link successfully but I get segfault when I try to run.

The problem is with the parsing of the net. After this line,

net = parse_network_cfg(cfgfile);

you can paste these lines,

layer l0 = net.layers[0];
cout << l0.w << endl;
layer l1 = net.layers[1];
cout << l1.w << endl;
layer l = net.layers[net.n - 1];
cout << l.w << endl;

to see exactly what I'm talking about.  The first layer looks good, but the data in all the layers after the first are complete garbage.

416
0            <--- garbage
32633    <--- garbage

However, If you run the .darknet-cpp executable, these lines give good data.

416
416
13

I also noticed, that when I set a breakpoint on the "net = parse_network_cfg()" line, I can't step into the function, but when running the executable, I can.

**Comment by prabindh** [comment]
It can happen because - the flags used to build the external wrapper application (that uses darknet-cpp-shared), does not match the flags used in the build of the library. Specifically, -DGPU and -DCUDNN. The network structure changes between the two (with and without these flags defined). Can you confirm ?

**Comment by prabindh** [comment]
Adding -DGPU and -DCUDNN to compile command fixed the problem.

**Comment by hacunamatada** [comment]
Comparing the .so version to the executable version, the library version seems to be running at least 30% slower. I want to know if this is normal behavior.

**Comment by prabindh** [comment]
Could you please raise a new issue (if it is not related to the issue in this thread ?)

Also, please confirm both versions are built with DEBUG=1

**Comment by D3Nd3R** [comment]
I linked with my cmake project, everithing is fine.
I can share CMakeLists.txt.

**Comment by prabindh** [comment]
Could you close the issue if it is not a real one ? Thanks.

**Comment by sigmoidx** [comment]
I can confirm that shared cpp library runs at max. 19 FPS in 1080p video. The original YOLO v2 runs avg. 29-32 FPS in 1080p. Both shared cpp library and YOLO v2 were built with GPU=1, CUDNN=1, OPENCV=1, DEBUG=0.

**Comment by prabindh** [comment]
Can you share the commit id of the tree you are using ? Also, what application are you linking the shared .so with - does that also have the same flags ?

**Comment by sigmoidx** [comment]
I do not know the commit id of the tree but am sure just downloaded all of them today. And the lagging performance of the one I just downloaded today (the latest one) is quite same with the one I had downloaded a month ago. Because I want a quick test, I made a test program to link darknet. It is a simple cpp program.

I made darknet.h to load the same things from darknet.c without main()

this is the testing program.

```
#include "darknet.h"
int main()
{
    run_test();    
    return 0;
}
```

and this is in darknet.h
`extern void run_test();`

and this is in detector.c
```
void run_test()
{    
   
    int *gpus = 0;
    int gpu = 0;
    int ngpus = 1;
    gpu_index = 0;
    int cam_index = 0;
    
    char* prefix;
        
    list *options = read_data_cfg("datacfgs/coco.data");
    int classes = option_find_int(options, "classes", 20);
    char *name_list = option_find_str(options, "names", "data/names.list");
    char **names = get_labels(name_list);
    demo("yolo.cfg", "yolo.weights", 0.2, cam_index, "Logan.mp4", names, classes, 0, prefix, 0.5);
}
```

As you see, there is no significant code changes in darknet codes. 

Thanks,

**Comment by prabindh** [comment]
Most likely this is result of the data transformation code, which now has the option of using a faster OpenCV API. Please check and re-open if needed.
