### ISSUE TITLE
Differences scores between Darknet and Arapaho

### ISSUE THREAD

**Issue by ooobelix** [prabindh/darknet#72]
Hi Prabindh,

I have predicted an image with the original darknet framework (_f6d861736038da22c9eb0739dca84003c5a5e275_).

I have predicted the same image with the very same configurations files, (i.e. cfg, weights) with Arapaho master and got difference : a wrong detection of person at 53,9%

I have tested with / without GPU / CUDNN without changes.

Did you change somethings on darknet framework?
Do you have an idea about this issue?
Is it related to Detection results are different from original code #47?

Thanks for your help.

**Comment by ooobelix** [comment]
I have tested this updated code from #47:
```
image ipl_to_image(IplImage* src);
[...]
IplImage ipl_img = inputRgb;
image im = ipl_to_image(&ipl_img);
image sized = letterbox_image( im, net->w, net->h );
__Detect( sized.data, thresh, hier_thresh, objectCount );
free_image( im );
free_image( sized );
```

It works well but I have the same issue on height.

**Comment by prabindh** [comment]
It should not have different results from algorithmic perspective. The issue you referenced in #47 is still unchanged.

**Comment by ooobelix** [comment]
You are right but my tests and the tests from #47 show an issue around IPLImage and cv::Mat. Do you have an idea or a fix?

**Comment by prabindh** [comment]
@ooobelix  Can you please check this letterbox resize and see if it works for your case - https://gist.github.com/prabindh/852787042c1f0246132ffa4b17f4e220

**Comment by ooobelix** [comment]
Thanks the pull request fixArapahoLibDarknetUsed, the results are very similar to original darknet/Python
