### ISSUE TITLE
Arapaho build issue

### ISSUE THREAD

**Issue by DNNlearning** [prabindh/darknet#76]
I'm trying to build Arapaho. I created the shared library and followed all the steps mentioned in arapaho_readme.txt and I get this error when making test app by running 'make arapaho':  

arapaho.cpp: In member function ‘bool ArapahoV2::Detect(const cv::Mat&, float, float, int&)’:
arapaho.cpp:235:37: error: ‘ipl_to_image’ was not declared in this scope
     image im = ipl_to_image(&ipl_img);

I can see that 'image.h' is being included in arapaho.hpp so I do not understand why it's giving me this error. It seems easy to fix, but I already spent way too much time to figure this out. Could you please kindly help me with this? Any suggestions are appreciated. Thanks.

**Comment by DNNlearning** [comment]
Funny thing, I fixed the issue just a few minutes after posting it. So it was because of two things that were missing from the instruction, might be useful for other users:
1 ) The Makefile in main directory had option OPENCV=1 and I used it to build the shared library. But this option was missing from the Makefile in 'arapaho' folder.
2 ) You would need to copy 'data' folder to 'arapaho' folder. It was giving me an error since it couldn't find coco.names

**Comment by prabindh** [comment]
Could you please push a patch for this if necessary ? Also there is a branch for opencv4 if you want to try out.

**Comment by DNNlearning** [comment]
Sorry, what do you mean by pushing a patch?
By the way, I tried to build Arapaho the next day and I did not change anything but the ‘ipl_to_image’ was not declared in this scope error showed up again. So bizarre. In order to fix it, I had to comment out or delete #ifdef OPENCV and the corresponding #endif lines in both src/image.h and src/image.c
