### ISSUE TITLE
Darknet saved weights are not giving outputs in this

### ISSUE THREAD

**Issue by spandanji** [prabindh/darknet#78]
Hello!
I am using your cv4-dev branch.
I had trained a single class object detector using yolov2 using AlexyAB's darknet build. after which I am able to get the images and the bounding boxes on them. I need the coordinates of the bounding boxes and hence wish to use your arapaho api . The model weights, cfg and the .data file and inference image were put as instructed but I am not getting the bounding box here. The code outputs 0 objects detected when the same gave 1 object detected previously.

**Comment by prabindh** [comment]
By the description it appears that the model was not trained with the standard darknet code-base ? If so, please note the training and inference are tied together. Please train with the standard darknet for using with the arapaho api. If you intend to use the other API, you can refer to https://github.com/AlexeyAB/darknet/blob/master/src/yolo_v2_class.cpp (std::vector<bbox_t> Detector::detect) that returns bounding boxes.

**Comment by spandanji** [comment]
Thanks a lot @prabindh . That fixed it for me!
