### ISSUE TITLE
Anyone tested darknet-cpp on Cuda 6.5 (Ubuntu 14.04)?

### ISSUE THREAD

**Issue by iamgiuly** [prabindh/darknet#79]
The following is my system configuration:
* Linux with Ubuntu 14.04 LTS
* CUDA 6.5
* cuDNN v2
* GeForce 840M 

Is possible to use darknet-cpp? I'm intrested on the C++ API (in particular GetBoxes() method), i'd like to integrate it in my c++ application.
Is there anyone who has tested the darknet wrapper in Ubuntu 14.04 with CUDA 6.5? 
Thanks

**Comment by prabindh** [comment]
I suspect full yolov3 would not run in this GPU.  Please first run the inference with original yolo, see which config of yolo fits (ex Yolo tiny?) in this. Then you can move it to use the c++ api.

**Comment by iamgiuly** [comment]
It works with this GPU. I tried the detector demo with coco dataset and with fully configuration file. How can i use the c++ api? Have I to compile only darknet-cpp or the entire framework? Is possible to compile only araphao interface into the darknet istance that I created? Sorry but I'm newbie in this informatic field.

**Comment by prabindh** [comment]
Please refer to https://github.com/prabindh/darknet/blob/master/arapaho/arapaho_readme.txt

To integrate arapaho into your application, you need to include the arapaho header, and link to the darknet-cpp shared lib. The arapaho test application shows how to do this.

**Comment by iamgiuly** [comment]
I get the following error during compilation:
<code>In file included from ./examples/instance-segmenter.c:1:0:
include/darknet.h:435:5: error: ‘cudnnConvolutionBwdDataAlgo_t’ does not name a type
     cudnnConvolutionBwdDataAlgo_t bd_algo;
     ^
compilation terminated due to -Wfatal-errors.
make: *** [obj-cpp-shared/instance-segmenter.o] Errore 1
</code>

**Comment by prabindh** [comment]
This algorithm is not supported in your version of CUDNN being used.
