### ISSUE TITLE
Trained in two classes the object can't be inference

### ISSUE THREAD

**Issue by sswtr** [prabindh/darknet#80]
I have trained in only single class and it correctly inference the object. 
But after I add a new another class, when I use the new trained weights, it can't inference both object. (It could be correctly inference by using https://github.com/AlexeyAB/darknet , but our streaming video inference are using arapaho)

**Comment by prabindh** [comment]
Are you able to get inference based on the tiny-yolo config to work ?

**Comment by sswtr** [comment]
Yes, I'm using tiny yolo cfg.
I have solve it by changing our image from BGR to RGB
Thanks your reply.

**Comment by prabindh** [comment]
Great, thanks for closing.
