### ISSUE TITLE
error "identifier \"ipl_to_image\" is undefined","LineNumber": 234, File: arapaho.cpp

### ISSUE THREAD

**Issue by DimasVeliz** [prabindh/darknet#81]
Hello, I am trying to execute the "make arapaho" command within its folder, but the compiler returns that "ipl_to_image" is undefined, I checked on the "image.c" file and the function exist, all the includes are set as they were on Github

![WhatsApp Image 2020-05-01 at 00 06 46](https://user-images.githubusercontent.com/49822685/80763881-cb67cf00-8b3f-11ea-8076-68ad59611d0c.jpeg)
![WhatsApp Image 2020-05-01 at 00 06 51](https://user-images.githubusercontent.com/49822685/80763886-cc006580-8b3f-11ea-856e-8b1fd69746fb.jpeg)

. 

From what I see, within  "/src/image.c" this function that is giving me problems and some others are only defined "ifdef OPENCV"

I correctly compiled both the darknet-cpp and the darknet-cpp-shared libraries. Flags for OPENCV,GPU,CUDNN are set equal to 1 on the MakeFile of darknet

I am using opencv version 3.2.0, it works well in C++ and Python3
I also have CUDA and CuNN installed and they work perfectly
I know the work cuz I can use darknet without problems with these flags activated,  Yolo3 in the original and tiny versions.

OS:Ubuntu 18.04

**Comment by prabindh** [comment]
Is OPENCV defined in arapaho ? ie, before image.h is included in arapaho.hpp ?

**Comment by prabindh** [comment]
To be clear - the build step of arapaho needs to define OPENCV, so that image.h sees it

**Comment by DimasVeliz** [comment]
It was all a problem with the opencv version :) I basically compiled that from source and adjusted, however after downloading the Nvidia Toolkit life became way easier as it installs Cuda, Cudnn and opencv in my computer and the JetsonTx2 I'm using 

Thanks for such a great proyect
